in_file = open('Text_9.4.txt', 'r')
text = in_file.read()
in_file.close()
text = text.replace('.', '')
text = text.replace(',', '')
text = text.replace('?', '')
text = text.replace('!', '')
text = text.replace(';', '')
text = text.replace(':', '')
text = text.replace('-', '')

text_list = text.split(' ')
text_set = set(text_list)
print(text_set)